const phrases = [
  "As I see it, yes",
  "Ask again later",
  "Better not tell you now",
  "Cannot predict now",
  "Don't count on it",
  "It is certain",
  "It is decidedly so",
  "Most likely",
  "My reply is no",
  "My sources say no",
  "Outlook good",
  "Outlook not so good",
  "Reply hazy try again",
  "Signs point to yes",
  "Very doubtful",
  "Without a doubt",
  "Yes",
  "Yes, definitely",
  "You may rely on it",
  "That's Ridiculous",
  "Ask Me If I Care",
  "Obviously",
  "In Your Dreams",
  "Sky's The Limit",
  "What Do You Think?",
];

export default phrases;
